###
GET http://localhost:3000/api/orders

###
GET http://localhost:3000/api/order/3


//users
###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/user/2
###
GET http://localhost:3000/api/userRelations/2

///reservations
###
GET http://localhost:3000/api/reservations

//!*reviwes
###
GET http://localhost:3000/api/reviews

//comments
###
GET http://localhost:3000/api/comments

//menu
###
GET http://localhost:3000/api/menu


// registration
###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullname": "John Doe",
    "image": "user1.jpg",
    "email": "johndoe@gmail.com",
    "password": "hashedpassword1",
    "phone": 1234567890,
    "role": "user"
}


//login
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "hashedpassword1"
}